server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mercado?useTimezone=true&serverTimezone=America/Sao_Paulo
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

  rabbitmq:
    request:
      host: localhost
      port: 5672
      username: guest
      password: guest
      exchange:
        producer: ex.producer.pedido
      routing-key:
        producer: rk.producer.pedido
      deadletter:
        producer: dl.producer.pedido

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

